apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: postgres
data:
  init-multiple-databases.sh: |
    #!/bin/bash
    set -e

    # Create databases
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
        CREATE DATABASE ghost;
        CREATE DATABASE gitea;
    EOSQL

