apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: postgresql
data:
  POSTGRES_DB: "gitea"
  POSTGRES_USER: "gitea"
  POSTGRES_PASSWORD: "gitea"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  # Health check script (tekrarı önlemek için)
  health-check.sh: |
    #!/bin/sh
    pg_isready -U gitea

