apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo
spec:
  type: LoadBalancer  # Tarayıcıdan erişmek istiyoruz
  ports:
    - port: 9898      # Dış kapı numarası (Tarayıcıya yazacağımız)
      targetPort: 9898 # Daire içindeki oda numarası (Pod'un portu)
  selector:
    app: podinfo      # Hangi etiketli podlara gidecek?