apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo
spec:
  type: NodePort  # Local cluster'da LoadBalancer çalışmaz, NodePort kullanıyoruz
  ports:
    - port: 9898      # Service'in iç portu
      targetPort: 9898 # Pod'un portu
      nodePort: 30301  # NodePort numarası (30000-32767 arası olmalı, zaten 30301 atanmış)
  selector:
    app: podinfo