apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: guestbook
spec:
  selector:
    app: guestbook
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # NodePort numarası (30000-32767 arası, 30080 = 80'i hatırlatması için)
  type: NodePort  # Tarayıcıdan erişmek için NodePort kullanıyoruz

